tryton : add Coog version and Copyright in Help Menu (About...)
coopengo/tryton-client pull request #1
Opened 2016-11-14 10:14 UTC by MikeSquall

This include the current version of Coog (1.10), the website link and the copyright for Coopengo. 

Feature #5107

2016-11-14 10:18 UTC, JCavallo requested changes

2016-11-14 10:18 UTC, JCavallo commented on tryton/gui/window/about.py
> +"""
Ca ne doit pas faire partie du code, c'est une question sur la pull request

2016-11-14 10:18 UTC, JCavallo commented on tryton/gui/window/about.py
> +        # replace self.win.set_website('http://tryton.org/')
Plutôt que les commentaires "Replace", mets juste une référence vers l'anomalie avant la première modif, ça devrait suffire.

\# MAR : Fix #5107 : Replace tryton references with Coog

2016-11-14 11:59 UTC, fredericlangevin approved these changes

2016-11-14 14:21 UTC, MikeSquall commented
Remarques prises en compte

2016-11-14 15:05 UTC, JCavallo approved these changes

2016-11-15 09:21 UTC, jmousset approved these changes
Ok, par contre, pourquoi avoir mis le commentaire vers l'issue dans le code ?

2016-11-15 10:02 UTC, JCavallo commented
Pour savoir pourquoi on a un diff dans le client :)

2016-11-15 12:45 UTC, merged