action, gui: support action dynamic title (Part 2)
coopengo/tryton-client pull request #11
Opened 2017-05-28 15:43 UTC by nidhalk

Ref #6274

2017-05-28 15:45 UTC, nidhalk commented
This pull request prerequesites the following trytond pull request:
https://github.com/coopengo/trytond/pull/12

2017-05-29 07:46 UTC, romainseon commented
ca donne quoi avec un print screen?

2017-05-29 08:25 UTC, JCavallo requested changes
Pour moi, ça devrait être géré côté serveur dans le get_action_values.

La seule modification côté client, c'est de passer le titre à la création

2017-05-29 08:25 UTC, JCavallo commented on tryton/action/main.py
> +                title = action.get('title', False)
juste title = action.get('title', False)

2017-06-23 08:58 UTC, closed without merging