Fix crash on focus out event
coopengo/tryton-client pull request #214
Opened 2022-10-20 09:37 UTC by antoine-roulin

Fix #24366

Do not pass event arguments to _focus_out methods which does not take any.

2022-10-20 09:42 UTC, jmousset approved these changes

2022-10-20 09:44 UTC, mpaulmier approved these changes

2022-10-20 09:56 UTC, MaximeCoopengo approved these changes

2022-10-20 10:06 UTC, nicoe commented
Le mieux c'est de synchroniser la signature de `_focus_out` dans `widget.py` (même répertoire) avec celle de 6.4 (à priori c'est un artefact du merge).

2022-10-20 12:13 UTC, nicoe requested changes
Le mieux c'est de synchroniser la signature de _focus_out dans widget.py (même répertoire) avec celle de 6.4 (à priori c'est un artefact du merge).

2022-10-20 13:05 UTC, AdrienBenduc commented
@JCavallo Tu reprends le sujets dans ta BU ?

2022-10-21 09:51 UTC, antoine-roulin commented
cf. https://github.com/coopengo/tryton/pull/215

2022-10-21 09:51 UTC, closed without merging