tryton: Allow to order dict schema by sequence
coopengo/tryton-client pull request #54
Opened 2018-11-12 15:08 UTC by AdrienBenduc

Fix #10315

2018-11-13 09:21 UTC, jmousset reviewed
Du coup, le cas en question ne peut pas être gérer par le code de la clé (pour gérer l'ordre) ?

2018-11-13 09:21 UTC, jmousset commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +                    if x[1].get('sequence_order', x[0]) is not None else x[0]):
si x[0] is None alors x[0] is None de toute façon.

2018-11-13 13:42 UTC, JCavallo requested changes

2018-11-13 13:42 UTC, JCavallo commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +                    if x[1].get('sequence_order', x[0]) is not None else x[0]):
Bloquant : Pour moi, l'api doit être que s'il y a un sequence_order il n'est pas None.

En gros, tu check si sequence_order existe. Si oui, tu fais direct x[1]['sequence_order'], et sinon x[0].

2018-11-13 16:32 UTC, JCavallo submitted a review, later dismissed

2018-11-13 16:32 UTC, JCavallo commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +            x[1].get('sequence_order', None) for x in self.keys.iteritems())
Pour moi il n'est pas forcément nécessaire d'itérer sur toute la liste, il suffit de regarder le premier

2018-11-13 16:32 UTC, JCavallo commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +                for key, val in value_ordered.iteritems():
juste `return value_ordered.iteritems()` suffit

2018-11-13 16:32 UTC, JCavallo commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +                for key, val in sorted(value.iteritems()):
idem

2018-11-13 16:32 UTC, JCavallo commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +                    key=lambda x: x[1].get('sequence_order', None)):
Pour moi dans ce cas, c'est `x[1]['sequence_order']`

2018-11-15 09:31 UTC, AdrienBenduc commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +            x[1].get('sequence_order', None) for x in self.keys.iteritems())
C'est un any sur un iterateur. Donc don't worry, on itère pas sur toute la liste ;)

2018-11-15 09:31 UTC, AdrienBenduc commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +                    key=lambda x: x[1].get('sequence_order', None)):
C'est du style ;)

2018-11-15 09:31 UTC, AdrienBenduc commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +                for key, val in value_ordered.iteritems():
C'est du style et sorted ne renvoie pas d'itérateur. Je préfère rester cohérent.

2018-11-15 09:31 UTC, AdrienBenduc commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +                for key, val in sorted(value.iteritems()):
idem ;)

2018-11-15 09:31 UTC, AdrienBenduc commented
@JCavallo Pas sympa le review request sur du style hein ;)

2018-11-15 10:05 UTC, AdrienBenduc commented
@JCavallo Done.

2018-11-15 16:47 UTC, JCavallo commented on tryton/gui/window/view_form/view/form_gtk/dictionary.py
> +            x[1].get('sequence_order', None) for x in self.keys.iteritems())
Ce que je veux dire, c'est que si le premier élément n'a pas l'attribut, on n'utilise pas de sequence, et si il en a un, si. Là dans le cas où aucun élément n'a l'attribut, on va se taper toute la liste ;)

2018-11-16 16:01 UTC, merged